version: "3"

services:
  minecraft:
    image: itzg/minecraft-server:java17
    stdin_open: true
    tty: true

    ports:
      - 25565:25565
      - 8123:8123
    volumes:
      - "./server:/data"
      # - "./plugins:/plugins"
    environment:
      TYPE: SPIGOT
      VERSION: 1.18-rc3

      USE_AIKAR_FLAGS: "true"
      MEMORY: 4G

      EULA: "true"
      ENABLE_RCON: "false"

      SPIGET_RESOURCES: 9089 # EssentialsX

    restart: on-failure

volumes:
  minecraft:
